export const TOGGLE_ADD_ITEM = 'TOGGLE_ADD_ITEM';

export const ADD_ITEM_TO_CATEGORY = 'ADD_ITEM_TO_CATEGORY';

export const BACK_TO_SHOPPING_LIST = 'BACK_TO_SHOPPING_LIST';

export const SEE_INFO_ITEM = 'SEE_INFO_ITEM';
