export const TOGGLE_ADD_ITEM = 'TOGGLE_ADD_ITEM';

export const ADD_ITEM_TO_CATEGORY = 'ADD_ITEM_TO_CATEGORY';

export const BACK_TO_SHOPPING_LIST = 'BACK_TO_SHOPPING_LIST';

export const SEE_INFO_ITEM = 'SEE_INFO_ITEM';

export const DELETE_ITEM_FROM_CATEGORIES = 'DELETE_ITEM_FROM_CATEGORIES';

export const ADD_TO_CURRENT_LIST = 'ADD_TO_CURRENT_LIST';

export const EDIT_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY';

export const DELETE_ITEM_FROM_CURRENT_LIST = 'DELETE_ITEM_FROM_CURRENT_LIST';

export const UPDATE_SHOPPING_LIST_NAME = 'UPDATE_SHOPPING_LIST_NAME';

export const OBTAIN_ITEM = 'OBTAIN_ITEM';

export const TOGGLE_EDIT = 'TOGGLE_EDIT';
